# Generated by Django 4.2.3 on 2023-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
